### PR TITLE
add ignoreJunk option

### PR DESCRIPTION
**Pull request by rocktimsaikia**
partially addresses this issue #21

### CODE REVIEW

**Comment by sindresorhus** [comment]
Do you actually need this? Because looking at this now, I cannot think of any scenario where I would not want to ignore junk files.

**Comment by rocktimsaikia** [comment]
@sindresorhus  I don't personally need it too. But I think it's good to keep the cli in sync with the actual API https://github.com/sindresorhus/cpy. Also, it's a backward compatible feature, and keeping the option available is not a bad idea imo.

**Comment by sindresorhus** [comment]
I don't remember why I added that option to `cpy`, but I would probably not have done so today unless someone had a clear use-case.

**Comment by sindresorhus** [comment]
> But I think it's good to keep the cli in sync with the actual API

I generally agree, but it also has to be make sense. For example, the `rename` option is not easily transferrable to the CLI.

**Comment by sindresorhus** [comment]
I'm going to pass on this for now. If there's a need, this PR can be reopened. Sorry to waste your time. I had not thought it through when opening the original issue about brining the options here. The concurrency option makes sense though.

**Pull request closed without merging**
