### PR TITLE
Require Node.js 12 and move to ESM

### PR DESCRIPTION
**Pull request by antongolub**
* update deps to the latest versions
* BREAKING CHANGE: require Node.js >=12
* add Node.js v16 to test matrix

### CODE REVIEW

**Comment by antongolub** [comment]
awaits https://github.com/sindresorhus/cpy/pull/87

**Comment by arhadthedev** [comment]
Is there any progress on the issue?

**Comment by antongolub** [comment]
@sindresorhus,

Let's land this change.

**Comment by sindresorhus** [comment]
Note that this cannot be related until https://github.com/sindresorhus/cpy-cli/issues/27 is resolved.

**Pull request merged**
